# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-16 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketdepth',
            name='market_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'OKCoin'), (2, 'Huobi Coin'), (3, 'China BTC')], verbose_name='Market Type'),
        ),
        migrations.AlterField(
            model_name='marketticker',
            name='market_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'OKCoin'), (2, 'Huobi Coin'), (3, 'China BTC')], verbose_name='Market Type'),
        ),
        migrations.AlterField(
            model_name='usermarketconfig',
            name='market_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'OKCoin'), (2, 'Huobi Coin'), (3, 'China BTC')], verbose_name='Market Type'),
        ),
    ]
